# tags: procedural-generation, maze, dfs, tilemap, grid-system
import pygame
import random

class MazeManager:
    """
    Maze generation and management module.
    Encapsulates DFS maze generation algorithm and basic grid drawing functions.
    
    Features:
    1. Uses Iterative DFS to generate a guaranteed connected maze.
    2. Provides standardized map drawing methods.
    """
    
    # Color Definitions (Class Constants)
    WALL_COLOR = (0, 0, 0)          # Wall (Black)
    PATH_COLOR = (255, 255, 255)    # Path (White)
    START_COLOR = (0, 255, 0)       # Start (Green)
    END_COLOR = (255, 0, 0)         # End (Red)
    
    # Tile Definitions
    TILE_WALL = 1
    TILE_PATH = 0
    TILE_START = 2
    TILE_END = 3

    def __init__(self, tile_size=20):
        """
        :param tile_size: Pixel size of each grid tile (default 20)
        """
        self.tile_size = tile_size

    def create_path_dfs(self, width, height):
        """
        Generates a maze map using Depth-First Search (DFS).
        
        :param width: Grid width (Cols)
        :param height: Grid height (Rows)
        :return: 2D array (List of Lists)
        """
        # Initialize grid with walls
        grid = [[self.TILE_WALL for _ in range(width)] for _ in range(height)]
        
        start_x, start_y = 1, 1
        grid[start_y][start_x] = self.TILE_PATH
        
        stack = [(start_x, start_y)]    # Track visited locations
        directions = [(0, -2), (0, 2), (-2, 0), (2, 0)]

        # DFS Algorithm excavation process
        while stack:
            current_x, current_y = stack[-1]
            possible_moves = []
            for dx, dy in directions:
                nx, ny = current_x + dx, current_y + dy
                if 1 <= nx < width - 1 and 1 <= ny < height - 1:
                    if grid[ny][nx] == self.TILE_WALL:
                        possible_moves.append((dx, dy))
            
            if possible_moves:
                dx, dy = random.choice(possible_moves)
                # Break through walls (middle tile and target tile)
                grid[current_y + dy // 2][current_x + dx // 2] = self.TILE_PATH
                grid[current_y + dy][current_x + dx] = self.TILE_PATH
                stack.append((current_x + dx, current_y + dy))
            else:
                stack.pop()

        # Define start and end points
        grid[1][1] = self.TILE_START
        grid[height - 2][width - 2] = self.TILE_END

        return grid

    def draw_map(self, surface, map_data):
        """
        Draws the entire maze map onto a designated Surface.
        
        :param surface: Target drawing canvas (usually 'screen')
        :param map_data: 2D array generated by create_path_dfs
        """
        # Fill background with path color; drawing only walls and special points optimizes performance
        surface.fill(self.PATH_COLOR)

        for row_index, row in enumerate(map_data):
            for col_index, tile in enumerate(row):
                rect = pygame.Rect(
                    col_index * self.tile_size, 
                    row_index * self.tile_size, 
                    self.tile_size, 
                    self.tile_size
                )
                
                if tile == self.TILE_WALL:
                    pygame.draw.rect(surface, self.WALL_COLOR, rect)
                elif tile == self.TILE_START:
                    pygame.draw.rect(surface, self.START_COLOR, rect)
                elif tile == self.TILE_END:
                    pygame.draw.rect(surface, self.END_COLOR, rect)